# Generated by Django 4.2.7 on 2023-11-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('numero', models.IntegerField()),
                ('generacion', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
